"""Deterministic operational intelligence services for Level 01 OBSERVE.

Maintains geographically coherent Antarctic vessel tracking positions
and iceberg hazards for the BOREAS command center.
"""

from datetime import datetime, timezone
from .models import (
    ObservedIceberg,
    ObservedVessel,
    IcebergsObserveResponse,
    VesselsObserveResponse,
)

# 10 Curated Antarctic Vessels (8 underway/active, 1 moored, 1 ice-bound)
_VESSELS_ROSTER: list[dict] = [
    {
        "id": "vasiliy_golovnin",
        "name": "MV Vasiliy Golovnin",
        "imo": "8723426",
        "mmsi": "273149510",
        "vessel_type": "Project 10620 icebreaking cargo ship",
        "ice_class": "Arc7 / ULA",
        "latitude": -68.85,
        "longitude": 75.80,
        "heading_deg": 185.0,
        "speed_kt": 8.5,
        "destination": "Bharati Station (Larsemann Hills)",
        "eta": "2026-09-22 06:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "UBUT",
        "flag": "Russia",
        "track_history": [
            [73.50, -64.20],
            [74.20, -65.80],
            [75.00, -67.10],
            [75.80, -68.85],
        ],
        "source": "PROTOTYPE AIS — DEAD RECKONING TRANSIT",
    },
    {
        "id": "ivan_papanin",
        "name": "MV Ivan Papanin",
        "imo": "8837928",
        "mmsi": "273137200",
        "vessel_type": "Ice-strengthened general cargo ship",
        "ice_class": "Arc5 / UL",
        "latitude": -62.40,
        "longitude": 14.50,
        "heading_deg": 165.0,
        "speed_kt": 11.2,
        "destination": "Maitri Station (Queen Maud Land)",
        "eta": "2026-09-25 18:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "UBRD",
        "flag": "Russia",
        "track_history": [
            [18.42, -34.20],
            [16.50, -45.00],
            [15.20, -55.00],
            [14.50, -62.40],
        ],
        "source": "PROTOTYPE AIS — ESTIMATED TRANSIT",
    },
    {
        "id": "sir_david_attenborough",
        "name": "RRS Sir David Attenborough",
        "imo": "9798222",
        "mmsi": "740405000",
        "vessel_type": "Polar research and logistics vessel",
        "ice_class": "Polar Class 5 (PC5)",
        "latitude": -66.20,
        "longitude": -67.50,
        "heading_deg": 205.0,
        "speed_kt": 10.4,
        "destination": "Rothera Research Station",
        "eta": "2026-09-21 14:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "ZDLP",
        "flag": "Falkland Islands",
        "track_history": [
            [-58.00, -52.00],
            [-62.00, -58.00],
            [-65.00, -63.00],
            [-67.50, -66.20],
        ],
        "source": "PROTOTYPE AIS — DEAD RECKONING TRANSIT",
    },
    {
        "id": "polarstern",
        "name": "RV Polarstern",
        "imo": "8013132",
        "mmsi": "211202460",
        "vessel_type": "Icebreaking research vessel",
        "ice_class": "PC3 / GL-100A5 ARC3",
        "latitude": -70.15,
        "longitude": -8.20,
        "heading_deg": 70.0,
        "speed_kt": 4.8,
        "destination": "Neumayer Station III / Atka Bay",
        "eta": "2026-09-23 09:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "DBLK",
        "flag": "Germany",
        "track_history": [
            [-12.00, -69.20],
            [-10.50, -69.80],
            [-9.20, -70.00],
            [-8.20, -70.15],
        ],
        "source": "PROTOTYPE AIS — SURVEY TRANSECT",
    },
    {
        "id": "nuyina",
        "name": "RSV Nuyina",
        "imo": "9797060",
        "mmsi": "503000183",
        "vessel_type": "Icebreaking research & resupply vessel",
        "ice_class": "Polar Class 3 (PC3)",
        "latitude": -67.80,
        "longitude": 77.40,
        "heading_deg": 140.0,
        "speed_kt": 9.6,
        "destination": "Davis Station (Vestfold Hills)",
        "eta": "2026-09-20 22:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "VMN3281",
        "flag": "Australia",
        "track_history": [
            [147.30, -43.00],
            [110.00, -55.00],
            [88.00, -63.00],
            [77.40, -67.80],
        ],
        "source": "PROTOTYPE AIS — COASTAL INGRESS",
    },
    {
        "id": "xue_long_2",
        "name": "MV Xue Long 2",
        "imo": "9829241",
        "mmsi": "413381260",
        "vessel_type": "Polar research icebreaker",
        "ice_class": "Polar Class 3 (PC3)",
        "latitude": -69.37,
        "longitude": 76.38,
        "heading_deg": 0.0,
        "speed_kt": 0.0,
        "destination": "Zhongshan Station",
        "eta": "ARRIVED / MOORED",
        "status": "MOORED",
        "callsign": "BNEB",
        "flag": "China",
        "track_history": [
            [76.00, -68.50],
            [76.20, -69.00],
            [76.38, -69.37],
        ],
        "source": "PROTOTYPE AIS — HARBOR POSITION",
    },
    {
        "id": "akademik_fedorov",
        "name": "RV Akademik Fedorov",
        "imo": "8519837",
        "mmsi": "273412710",
        "vessel_type": "Icebreaking research-supply vessel",
        "ice_class": "Arc7 / ULA",
        "latitude": -65.90,
        "longitude": 92.50,
        "heading_deg": 125.0,
        "speed_kt": 10.1,
        "destination": "Mirny Station",
        "eta": "2026-09-24 12:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "UBEX",
        "flag": "Russia",
        "track_history": [
            [78.00, -58.00],
            [84.00, -61.00],
            [89.00, -64.00],
            [92.50, -65.90],
        ],
        "source": "PROTOTYPE AIS — ESTIMATED TRANSIT",
    },
    {
        "id": "agulhas_ii",
        "name": "SA Agulhas II",
        "imo": "9579690",
        "mmsi": "601835000",
        "vessel_type": "Polar research & supply vessel",
        "ice_class": "DNV ICE-10 / PC5",
        "latitude": -54.30,
        "longitude": 3.20,
        "heading_deg": 195.0,
        "speed_kt": 12.0,
        "destination": "SANAE IV / Penguin Bukta",
        "eta": "2026-09-26 15:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "ZRSE",
        "flag": "South Africa",
        "track_history": [
            [18.42, -34.00],
            [12.00, -42.00],
            [6.00, -49.00],
            [3.20, -54.30],
        ],
        "source": "PROTOTYPE AIS — OPEN-WATER TRANSIT",
    },
    {
        "id": "le_commandant_charcot",
        "name": "Le Commandant Charcot",
        "imo": "9841043",
        "mmsi": "578001800",
        "vessel_type": "Polar exploration cruise vessel (Hybrid PC2)",
        "ice_class": "Polar Class 2 (PC2)",
        "latitude": -69.50,
        "longitude": -80.20,
        "heading_deg": 110.0,
        "speed_kt": 7.2,
        "destination": "Peter I Island / Bellingshausen Sea",
        "eta": "2026-09-22 20:00 UTC",
        "status": "DEAD_RECKONING",
        "callsign": "FIAV",
        "flag": "France",
        "track_history": [
            [-71.00, -53.50],
            [-76.00, -61.00],
            [-79.00, -66.50],
            [-80.20, -69.50],
        ],
        "source": "PROTOTYPE AIS — TOUR EXPEDITION",
    },
    {
        "id": "kronprins_haakon",
        "name": "RV Kronprins Haakon",
        "imo": "9739587",
        "mmsi": "257277000",
        "vessel_type": "Polar research vessel",
        "ice_class": "Polar Class 3 (PC3)",
        "latitude": -68.40,
        "longitude": 0.80,
        "heading_deg": 85.0,
        "speed_kt": 1.2,
        "destination": "Troll Station offload / Astrid Coast",
        "eta": "2026-09-23 11:00 UTC",
        "status": "ICE_BOUND",
        "callsign": "LLYS",
        "flag": "Norway",
        "track_history": [
            [0.20, -67.50],
            [0.50, -68.00],
            [0.80, -68.40],
        ],
        "source": "PROTOTYPE AIS — CONCENTRATED ICE HOLD",
    },
]

# 10 Tracked Icebergs (Giant tabular megabergs + regional coastal hazards)
_ICEBERGS_ROSTER: list[dict] = [
    {
        "id": "A-23A",
        "name": "Megaberg A-23A",
        "latitude": -59.85,
        "longitude": -44.20,
        "drift_speed_kt": 1.4,
        "heading_deg": 42.0,
        "length_m": 60000.0,
        "width_m": 52000.0,
        "thickness_m": 380.0,
        "area_km2": 3120.0,
        "risk_level": "critical",
        "origin": "Filchner-Ronne Ice Shelf",
        "confidence": 0.94,
        "track_history": [
            [-48.50, -63.50],
            [-47.00, -62.00],
            [-45.50, -60.80],
            [-44.20, -59.85],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
    {
        "id": "D-28",
        "name": "Iceberg D-28 (Moo Cow)",
        "latitude": -65.40,
        "longitude": 70.20,
        "drift_speed_kt": 0.7,
        "heading_deg": 290.0,
        "length_m": 28000.0,
        "width_m": 18000.0,
        "thickness_m": 210.0,
        "area_km2": 504.0,
        "risk_level": "high",
        "origin": "Amery Ice Shelf (Prydz Bay Calving)",
        "confidence": 0.91,
        "track_history": [
            [73.50, -66.80],
            [72.20, -66.10],
            [71.10, -65.70],
            [70.20, -65.40],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
    {
        "id": "B-15AB",
        "name": "Iceberg B-15AB",
        "latitude": -64.10,
        "longitude": -142.50,
        "drift_speed_kt": 0.5,
        "heading_deg": 310.0,
        "length_m": 14000.0,
        "width_m": 9000.0,
        "thickness_m": 190.0,
        "area_km2": 126.0,
        "risk_level": "guarded",
        "origin": "Ross Ice Shelf",
        "confidence": 0.85,
        "track_history": [
            [-138.00, -65.80],
            [-139.50, -65.10],
            [-141.00, -64.60],
            [-142.50, -64.10],
        ],
        "detection_source": "NIC Radar",
        "source": "DERIVED TRACK — BYE/NIC DATABASE",
    },
    {
        "id": "B-17",
        "name": "Iceberg B-17",
        "latitude": -64.00,
        "longitude": -35.00,
        "drift_speed_kt": 0.6,
        "heading_deg": 78.0,
        "length_m": 4200.0,
        "width_m": 1700.0,
        "thickness_m": 200.0,
        "area_km2": 7.1,
        "risk_level": "guarded",
        "origin": "Ross Ice Shelf (Circumpolar Drift)",
        "confidence": 0.82,
        "track_history": [
            [-56.00, -63.00],
            [-50.00, -64.00],
            [-43.00, -65.00],
            [-35.00, -64.00],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
    {
        "id": "B-18",
        "name": "Iceberg B-18",
        "latitude": -68.00,
        "longitude": 37.00,
        "drift_speed_kt": 0.9,
        "heading_deg": 112.0,
        "length_m": 6800.0,
        "width_m": 2700.0,
        "thickness_m": 230.0,
        "area_km2": 18.4,
        "risk_level": "high",
        "origin": "Amery Ice Shelf drift remnant",
        "confidence": 0.75,
        "track_history": [
            [18.00, -66.00],
            [26.00, -67.00],
            [32.00, -68.00],
            [37.00, -68.00],
        ],
        "detection_source": "NIC Radar",
        "source": "DERIVED TRACK — BYE/NIC DATABASE",
    },
    {
        "id": "B-19",
        "name": "Iceberg B-19",
        "latitude": -71.00,
        "longitude": -89.00,
        "drift_speed_kt": 0.4,
        "heading_deg": 94.0,
        "length_m": 3100.0,
        "width_m": 1400.0,
        "thickness_m": 160.0,
        "area_km2": 4.3,
        "risk_level": "low",
        "origin": "Bellingshausen Sea ice tongue",
        "confidence": 0.90,
        "track_history": [
            [-122.00, -69.00],
            [-112.00, -70.00],
            [-101.00, -71.00],
            [-89.00, -71.00],
        ],
        "detection_source": "Sentinel-2",
        "source": "SYNTHETIC OPTICAL FIX — CDSE GROUNDED",
    },
    {
        "id": "C-38",
        "name": "Iceberg C-38",
        "latitude": -63.70,
        "longitude": 98.40,
        "drift_speed_kt": 0.8,
        "heading_deg": 275.0,
        "length_m": 8500.0,
        "width_m": 4200.0,
        "thickness_m": 220.0,
        "area_km2": 35.7,
        "risk_level": "high",
        "origin": "Shackleton Ice Shelf",
        "confidence": 0.88,
        "track_history": [
            [102.00, -64.20],
            [100.50, -64.00],
            [99.20, -63.80],
            [98.40, -63.70],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
    {
        "id": "A-76A",
        "name": "Iceberg A-76A",
        "latitude": -53.20,
        "longitude": -41.80,
        "drift_speed_kt": 1.6,
        "heading_deg": 35.0,
        "length_m": 35000.0,
        "width_m": 15000.0,
        "thickness_m": 260.0,
        "area_km2": 525.0,
        "risk_level": "guarded",
        "origin": "Ronne Ice Shelf",
        "confidence": 0.89,
        "track_history": [
            [-45.00, -56.00],
            [-44.00, -55.00],
            [-43.00, -54.00],
            [-41.80, -53.20],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
    {
        "id": "PB-04",
        "name": "Prydz Bay Calving PB-04",
        "latitude": -68.65,
        "longitude": 77.85,
        "drift_speed_kt": 0.3,
        "heading_deg": 245.0,
        "length_m": 2400.0,
        "width_m": 1100.0,
        "thickness_m": 140.0,
        "area_km2": 2.6,
        "risk_level": "high",
        "origin": "Sørsdal Glacier Tongue (Vestfold Hills)",
        "confidence": 0.95,
        "track_history": [
            [78.50, -68.50],
            [78.20, -68.58],
            [78.00, -68.62],
            [77.85, -68.65],
        ],
        "detection_source": "Sentinel-2",
        "source": "SYNTHETIC OPTICAL FIX — CDSE GROUNDED",
    },
    {
        "id": "PB-09",
        "name": "Prydz Bay Tabular PB-09",
        "latitude": -69.05,
        "longitude": 75.30,
        "drift_speed_kt": 0.2,
        "heading_deg": 315.0,
        "length_m": 1800.0,
        "width_m": 950.0,
        "thickness_m": 120.0,
        "area_km2": 1.7,
        "risk_level": "guarded",
        "origin": "Publications Ice Shelf (Near-Bharati)",
        "confidence": 0.93,
        "track_history": [
            [75.80, -69.15],
            [75.60, -69.10],
            [75.40, -69.07],
            [75.30, -69.05],
        ],
        "detection_source": "Sentinel-1",
        "source": "SYNTHETIC RADAR TRACK — CDSE GROUNDED",
    },
]


def get_observed_vessels() -> VesselsObserveResponse:
    """Returns deterministic Antarctic vessel traffic observation picture."""
    vessels = [ObservedVessel(**data) for data in _VESSELS_ROSTER]
    active_count = sum(1 for v in vessels if v.status in ("LIVE_AIS", "DEAD_RECKONING"))
    return VesselsObserveResponse(
        vessels=vessels,
        total_count=len(vessels),
        active_count=active_count,
        provenance="PROTOTYPE AIS — DETERMINISTIC ANTARCTIC FLEET",
        updated_at=datetime.now(timezone.utc).isoformat(),
    )


def get_observed_icebergs() -> IcebergsObserveResponse:
    """Returns deterministic tracked iceberg hazard picture."""
    icebergs = [ObservedIceberg(**data) for data in _ICEBERGS_ROSTER]
    return IcebergsObserveResponse(
        icebergs=icebergs,
        total_count=len(icebergs),
        provenance="SYNTHETIC RADAR/OPTICAL TRACKS — DETERMINISTIC RECON",
        updated_at=datetime.now(timezone.utc).isoformat(),
    )
