"""BOREAS shore<->ship coordination: shared mission/vessel/route-update
state so the Shore and Ship applications agree on what is happening to a
single vessel, without a message broker -- simple REST state, polled.
"""

from .models import (
    ActivateRouteRequest,
    ActiveRoute,
    MissionInfo,
    OriginSnapshot,
    RouteUpdate,
    RouteUpdateCreate,
    RouteUpdateRespond,
    RouteUpdateStatus,
    SetSpeedRequest,
    SimulateChangeRequest,
    VesselState,
)
from .service import (
    PAUSE_AWAITING_DECISION,
    SPEED_MULTIPLIERS,
    MissionNotFound,
    RouteUpdateAlreadyResolved,
    RouteUpdateNotFound,
    activate_route,
    compute_vessel_state,
    create_route_update,
    describe_route_change,
    get_active_route,
    get_mission_info,
    get_route_update,
    list_route_updates,
    pause_vessel,
    respond_to_update,
    resume_vessel,
    set_speed_multiplier,
)

__all__ = [
    "ActivateRouteRequest",
    "ActiveRoute",
    "MissionInfo",
    "OriginSnapshot",
    "RouteUpdate",
    "RouteUpdateCreate",
    "RouteUpdateRespond",
    "RouteUpdateStatus",
    "SetSpeedRequest",
    "SimulateChangeRequest",
    "SPEED_MULTIPLIERS",
    "PAUSE_AWAITING_DECISION",
    "VesselState",
    "MissionNotFound",
    "RouteUpdateAlreadyResolved",
    "RouteUpdateNotFound",
    "activate_route",
    "compute_vessel_state",
    "create_route_update",
    "describe_route_change",
    "get_active_route",
    "get_mission_info",
    "get_route_update",
    "list_route_updates",
    "pause_vessel",
    "respond_to_update",
    "resume_vessel",
    "set_speed_multiplier",
]
